prod:
  image: vfarcic/books-service
  volumes:
    - /data/db:/data/db
  ports:
      - 8080:8080
  links:
    db
db:
  image: mongo
feTestsWatch:
  image: vfarcic/books-service-tests
  dockerfile: Dockerfile.test
  stdin_open: true
  tty: true
  volumes:
    - /data/.ivy2:/root/.ivy2/cache
    - .:/source
    - db:/data/db
  ports:
    - 8080:8080
  environment:
    - TEST_TYPE=watch-front