app:
  image: vfarcic/books-service
  ports:
    - 8080
  volumes:
    - /data/db:/data/db

tests:
  image: vfarcic/books-service-tests
  volumes:
    - client/components:/source/client/components
    - client/test:/source/client/test
    - src:/source/src
    - target/scala-2.10:/source/target/scala-2.10
    - client/wct-complete.conf.js:/source/client/wct.conf.js
    - /data/tests/db:/data/db
  environment:
    - TEST_TYPE=all

integ:
  image: vfarcic/books-service-tests
  volumes:
    - src:/source/src
  environment:
    - TEST_TYPE=integ

feTestsWatch:
  image: vfarcic/books-service-tests
  dockerfile: Dockerfile.test
  stdin_open: true
  tty: true
  volumes:
    - client/components:/source/client/components
    - client/test:/source/client/test
    - src:/source/src
    - target:/source/target
    - /data/tests/db:/data/db
  ports:
    - 8080:8080
  environment:
    - TEST_TYPE=watch-front